### ISSUE TITLE
ERROR: Unable to communicate with master!

### ISSUE THREAD

**Issue by andrestoga** [boschresearch/pcg_gazebo#127]
When running the following code in a ROS melodic package:

https://boschresearch.github.io/pcg_gazebo_pkgs/tutorials/simulation/model_generator/

I'm getting the following error even though Gazebo starts and master is running in another terminal:

```
~/ros/world_generator$ rosrun testing testing.py 
ERROR: Unable to communicate with master!
2020-10-13 23:09:42,801 | WARNING | __init__ | Error testing Gazebo server, message=Command '['rostopic', 'list']' returned non-zero exit status 1
['gazebo']
Is Gazebo running: False
ERROR: Unable to communicate with master!
ERROR: Unable to communicate with master!
2020-10-13 23:09:43,169 | WARNING | __init__ | Error testing roscore, message=Command '['rostopic', 'list']' returned non-zero exit status 1
2020-10-13 23:09:43,170 | WARNING | __init__ | Error testing Gazebo server, message=Command '['rostopic', 'list']' returned non-zero exit status 1
ERROR: Unable to communicate with master!
2020-10-13 23:09:43,578 | WARNING | __init__ | Error testing roscore, message=Command '['rostopic', 'list']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/andrestoga/ros/world_generator/src/packages/testing/scripts/testing.py", line 62, in <module>
    create_and_spawn(config)
  File "/home/andrestoga/ros/world_generator/src/packages/testing/scripts/testing.py", line 47, in create_and_spawn
    2 * random.random()])
  File "/home/andrestoga/.local/lib/python2.7/site-packages/pcg_gazebo/generators/world_generator.py", line 329, in spawn_model
    reference_frame)
  File "/home/andrestoga/.local/lib/python2.7/site-packages/pcg_gazebo/task_manager/gazebo_proxy.py", line 372, in spawn_sdf_model
    reference_frame)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 532, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: receive_once[/gazebo/spawn_sdf_model]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
```

The same error happens in a Jupyter notebook and a stand-alone python script with python2.7

**Comment by tolgabuyuktanir** [comment]
Have you solved this problem?
